import React,{useEffect,useState} from 'react';
import {Search,ArrowRight,ExternalLink,Globe,Check,FileText,AlertCircle,Settings,ChevronDown} from 'lucide-react';

const list=v=>Array.isArray(v)?v:[];
const host=url=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return '来源未提供'}};
const stamp=value=>value?new Date(value).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}):'时间未提供';
const preferred=items=>items.filter(c=>c.relevance==='matched'&&!completed(c)).slice(0,3).map(c=>c.id);
const completed=c=>['imported','added','existing','already_imported','duplicate'].includes(c.import_status||c.status);

export function FocusOptions({value,onChange}){
 return <div className="search-focus" aria-label="搜索侧重">{[['general','综合了解'],['official','优先官方'],['perspectives','补充不同视角']].map(([key,label])=><button key={key} className={value===key?'active':''} onClick={()=>onChange(key)} aria-pressed={value===key}>{label}</button>)}</div>;
}

export default function SearchPanel({question,onSearch,onImport,onSource,onAnalyze,onChanges,onAddSource,onSettings,busy,provider}){
 const report=question.search_report;
 const candidates=list(report?.candidates);
 const [query,setQuery]=useState(list(report?.actual_queries)[0]||report?.query||question.title),[focus,setFocus]=useState('general'),[selected,setSelected]=useState([]);
 useEffect(()=>{setQuery(list(report?.actual_queries)[0]||report?.query||question.title);setSelected(preferred(candidates))},[question.id,report?.searched_at]);
 useEffect(()=>{setSelected(v=>v.filter(id=>!candidates.some(c=>c.id===id&&completed(c))))},[question.search_import_report]);
 const importReport=question.search_import_report;
 const results=list(importReport?.items||importReport?.import_results||importReport?.results);
 const failed=results.filter(r=>['failed','error'].includes(r.status));
 const imported=results.filter(r=>!['failed','error','skipped'].includes(r.status));
 const hasSources=list(question.source_ids).length>0;
 const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):v.length<8?[...v,id]:v);
 const actualQueries=list(report?.actual_queries).length?report.actual_queries:report?.query?[report.query]:[];
 const weakCandidates=candidates.filter(c=>c.relevance==='partial');
 return <section className="search-page">
  <div className="search-page-heading"><div className="eyebrow"><Globe size={14}/>围绕同一个问题，继续找依据</div><h2>{report?'先看来源，再决定读什么。':'把问题交给搜索，从这里开始。'}</h2><p>搜索给出线索；选中后，知向才会读取原文、保存资料并分析。</p></div>
  <form className="search-again" onSubmit={e=>{e.preventDefault();onSearch(question.title,focus,true)}}><label htmlFor="search-query">让知向自动整理搜索计划</label><div className="search-again-input"><Search size={18}/><span className="auto-search-copy">从你的问题开始，自动生成中文、英文、官方来源等搜索角度</span><button className="primary" disabled={busy} type="submit">{report?'重新探索':'开始联网搜索'}<ArrowRight size={15}/></button></div><details className="manual-search"><summary>高级选项：手动填写搜索词</summary><div className="search-again-input"><Search size={18}/><input id="search-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如：公司名称、年份、年报；填写后将直接搜索"/><button className="secondary" disabled={busy||!query.trim()} type="button" onClick={()=>onSearch(query,focus,false)}>直接搜索</button></div><p className="direct-search-note">手动搜索会跳过 AI 搜索计划，适合你已经明确知道关键词的情况。</p></details></form>
  <FocusOptions value={focus} onChange={setFocus}/>
  {report&&<div className="search-context"><span><Globe size={13}/>{report.provider==='tavily'?'Tavily 搜索':report.provider_name||'公共搜索'} · {stamp(report.searched_at)}</span><span>找到 {candidates.length} 条线索</span></div>}
  {report&&<div className="query-trace"><div className="query-trace-heading"><Search size={15}/><strong>这次实际执行的搜索</strong><span>{{model:'AI 整理后搜索',direct:'使用你填写的搜索词',fallback:'直接搜索'}[report.query_plan?.mode]||'公开来源搜索'}</span></div><ol>{actualQueries.map((text,i)=><li key={i}>{text}</li>)}</ol>{report.query_plan?.notice&&<p>{report.query_plan.notice}</p>}{list(report.failed_queries).length>0&&<details><summary>另有 {report.failed_queries.length} 次查询未完成<ChevronDown size={13}/></summary>{report.failed_queries.map((item,i)=><p key={i}><strong>{item.query}</strong><br/>{item.message}</p>)}</details>}</div>}
  {report?.notice&&<div className="search-notice"><AlertCircle size={16}/><p>{report.notice}</p></div>}
  {!!results.length&&<div className="import-report"><div className="import-report-heading"><FileText size={17}/><strong>上次读取：{imported.length} 份可用{failed.length?`，${failed.length} 份未读到正文`:''}</strong></div><p>成功读取的正文已加入资料。未读到的网页仍是线索，不会把搜索摘要当成正文。</p><details><summary>逐条查看读取结果<ChevronDown size={13}/></summary>{results.map((r,i)=><div className={'import-result '+(['failed','error'].includes(r.status)?'failed':'')} key={r.candidate_id||i}><span>{['failed','error'].includes(r.status)?'未读到正文':['existing','duplicate','already_imported'].includes(r.status)?'已有资料':'已读取'}</span><div><strong>{r.title||candidates.find(c=>c.id===(r.candidate_id||r.id))?.title||r.url||'所选来源'}</strong>{(r.error||r.message)&&<p>{r.error||r.message}</p>}{r.source_id&&<button className="text-link" onClick={()=>onSource(r.source_id)}>查看已保存原文<ArrowRight size={12}/></button>}</div></div>)}</details>{importReport.analysis_error&&<div className="search-notice"><AlertCircle size={15}/><p>正文已保留，但这次分析未完成：{importReport.analysis_error}</p></div>}{hasSources&&<div className="import-next"><button className="secondary compact" onClick={question.judgment?onChanges:onAnalyze}>{question.judgment?'对照新材料与我的判断':question.analysis?'查看这次分析':'分析已保存的资料'}<ArrowRight size={14}/></button>{failed.length>0&&<button className="text-link" onClick={onAddSource}>也可以粘贴未读到的原文</button>}</div>}</div>}
  {candidates.length>0?<><div className="candidate-heading"><div><h3>这次找到的公开线索</h3><p>已选 {selected.length} 条，最多 8 条；优先初选关键词匹配的来源，可手动调整。</p></div><div className="candidate-top-actions"><button className="subtle" disabled={!selected.length&&!preferred(candidates).length} onClick={()=>setSelected(selected.length?[]:preferred(candidates))}>{selected.length?'取消选择':preferred(candidates).length?'选择较匹配来源':'可手动选择来源'}</button><button className="primary compact" disabled={busy||!selected.length} onClick={()=>onImport(selected)}>{question.judgment?'读取并加入新材料':'读取原文并分析'}<ArrowRight size={14}/></button></div></div>{weakCandidates.length>0&&<div className="weak-candidates-note"><AlertCircle size={14}/><span>其中 {weakCandidates.length} 条只匹配部分关键词，未默认选中。关键词匹配帮助筛选线索，不能验证事实。</span></div>}<div className="candidate-grid">{candidates.map((c,index)=><article className={'candidate-card '+(selected.includes(c.id)?'selected ':'')+(completed(c)?'imported':'')} key={c.id}><div className="candidate-top"><label className="candidate-check"><input type="checkbox" checked={selected.includes(c.id)} disabled={completed(c)||busy||(!selected.includes(c.id)&&selected.length>=8)} onChange={()=>toggle(c.id)}/><span>{completed(c)?<><Check size={13}/>已加入资料</>:`线索 ${String(index+1).padStart(2,'0')}`}</span></label><a href={c.url} target="_blank" rel="noreferrer" aria-label={`打开来源：${c.title}`} title="打开来源网页"><ExternalLink size={16}/></a></div><h3><a href={c.url} target="_blank" rel="noreferrer">{c.title||'未提供标题的网页'}</a></h3><div className="candidate-meta"><span>{c.publisher||host(c.url)}</span><span>{c.published_at||'发布日期未知'}</span></div><div className={'candidate-relevance '+(c.relevance==='partial'?'partial':'')}><span>{c.relevance==='partial'?'关键词仅部分匹配':c.relevance==='matched'?'关键词匹配':'相关性尚待确认'}</span><p>{c.relevance_notice||'是否切题，需要阅读原文判断。'}</p></div><div className="candidate-snippet"><span>搜索摘要 · {completed(c)?'正文见已保存资料':'尚未读取正文'}</span><p>{c.snippet||'搜索服务没有提供摘要，可先打开来源查看。'}</p></div><div className="candidate-domain">{host(c.url)}{(c.import_status||c.status)==='failed'&&<span>上次未读到正文，可重试</span>}</div>{c.import_error&&<p className="candidate-read-error">{c.import_error}</p>}{c.source_id&&<button className="text-link" onClick={()=>onSource(c.source_id)}>查看已保存原文<ArrowRight size={12}/></button>}</article>)}</div><div className="search-selection-bar"><div><strong>已选 {selected.length} 条线索</strong><p>{question.judgment?'读取后加入新材料，原判断继续保留。':'下一步会读取原文，用成功读取的材料整理分析。'}</p></div><button className="primary" disabled={busy||!selected.length} onClick={()=>onImport(selected)}>{question.judgment?'读取并加入新材料':'读取原文并分析'}<ArrowRight size={16}/></button></div></>:<div className="search-empty"><Search size={28}/><h3>{report?'这次没有找到可用线索':'从一个问题开始找资料'}</h3><p>{report?'试着缩短问题，写清公司、产品或年份，再搜一次。公共搜索可能暂时不可用，也可以在设置里切换搜索服务。':'不必先找到链接。输入你想核实的内容，就能看到可以选择的公开来源。'}</p>{report&&<button className="secondary compact" onClick={onSettings}><Settings size={14}/>查看搜索设置</button>}</div>}
  <div className="search-bottom-note"><Globe size={14}/><span>{provider==='tavily'?'搜索使用你配置的 Tavily。':'默认使用免 Key 公共搜索，可用性受外部服务影响。'} 搜索词会发送给搜索服务；DeepSeek 整理搜索词与分析原文时使用模型额度。</span></div>
 </section>;
}
